package com.google.cloud.tools.eclipse.usagetracker;

import org.eclipse.osgi.util.NLS;

/**
 * Resource bundle for localization. Automatically generated by Eclipse Externalize Strings Wizard.
 */
public class Messages extends NLS {
  private static final String BUNDLE_NAME = "com.google.cloud.tools.eclipse.usagetracker.messages";
  public static String OPT_IN_DIALOG_TITLE;
  public static String OPT_IN_DIALOG_TEXT;
  public static String OPT_IN_BUTTON;
  public static String OPT_OUT_BUTTON;
  static {
    // initialize resource bundle
    NLS.initializeMessages(BUNDLE_NAME, Messages.class);
  }

  private Messages() {
  }
}
